checkout code manual windows runner

diff --git a/.github/workflows/build-deploy-webgl.yml b/.github/workflows/build-deploy-webgl.yml
--- a/.github/workflows/build-deploy-webgl.yml
+++ b/.github/workflows/build-deploy-webgl.yml
@@ -6,59 +6,90 @@ env:
   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
 jobs:
-  checkLicense:
-    name: Check for the Unity license ☑️
-    runs-on: ubuntu-latest
-    steps:
-      - name: Fail - No license ☠️
-        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
-        run: exit 1
+  # checkLicense:
+  #   name: Check for the Unity license ☑️
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Fail - No license ☠️
+  #       if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
+  #       run: exit 1
 
   buildWebGL:
-    needs: checkLicense
+    # needs: checkLicense
     name: Build WebGL
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          ref: master
-
-      - name: Create LFS file list
-        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
-
-      - name: Restore LFS cache
-        uses: actions/cache@v2
-        id: lfs-cache
-        with:
-          path: .git/lfs
-          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
-
-      - name: Git LFS Pull
+      - name: Checkout code manual
         run: |
-          git lfs pull
-          git add .
-          git reset --hard
+          git --version
+          git init
 
-      - name: Restore Library cache
-        uses: actions/cache@v3
-        with:
-          path: Library
-          key: Library-build-WebGL
-          restore-keys: |
-            Library-build-
-            Library-
+          git config --global core.compression 0
+          git config --global core.packedGitLimit 512m
+          git config --global core.packedGitWindowSize 512m
 
-      - name: Build WebGL
-        uses: game-ci/unity-builder@v4
-        env:
-          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
-          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
-          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
-        with:
-          targetPlatform: WebGL
-          buildsPath: Client
-          buildName: Roguelike
+          git config --global pack.window 1
+          git config --global pack.windowMemory 4096m
+          git config --global pack.packSizeLimit 2048m
+          git config --global pack.deltaCacheSize 2048m
+
+          git config --global http.version HTTP/1.1
+          git config --global http.postBuffer 1024M
+          git config --global http.maxRequestBuffer 512M
+
+          git config --global pack.window 1
+
+          set GIT_TRACE_PACKET=1
+          set GIT_TRACE=1
+          set GIT_CURL_VERBOSE=1
+
+          mkdir .ssh
+          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa.pub
+          echo "${{ secrets.SSH_PRIVATE }}" > ~/.ssh/id_rsa
+
+          git remote add origin git@github.com:quangnguyen11/game-ci-test.git
+          git clone git@github.com:quangnguyen11/game-ci-test.git
+          git checkout master
+      # - name: Checkout code
+      #   uses: actions/checkout@v3
+      #   with:
+      #     ref: master
+
+      # - name: Create LFS file list
+      #   run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
+
+      # - name: Restore LFS cache
+      #   uses: actions/cache@v2
+      #   id: lfs-cache
+      #   with:
+      #     path: .git/lfs
+      #     key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
+
+      # - name: Git LFS Pull
+      #   run: |
+      #     git lfs pull
+      #     git add .
+      #     git reset --hard
+
+      # - name: Restore Library cache
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: Library
+      #     key: Library-build-WebGL
+      #     restore-keys: |
+      #       Library-build-
+      #       Library-
+
+      # - name: Build WebGL
+      #   uses: game-ci/unity-builder@v4
+      #   env:
+      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
+      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
+      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+      #   with:
+      #     targetPlatform: WebGL
+      #     buildsPath: Client
+      #     buildName: Roguelike
 
       # to show artifact of builf in Github action uncomment these lines
       # - name: Upload artifact to GH
@@ -67,12 +98,12 @@ jobs:
       #     name: build-WebGL
       #     path: build/WebGL
 
-      - name: Push Build to branch build/webgl
-        run: |
-          ls -R
-          git config user.name quangnguyen11
-          git config user.email quang888@gmail.com
-          git checkout build/webgl
-          git add Client
-          git commit -m "build webgl `date`"
-          git push
+      # - name: Push Build to branch build/webgl
+      #   run: |
+      #     ls -R
+      #     git config user.name quangnguyen11
+      #     git config user.email quang888@gmail.com
+      #     git checkout build/webgl
+      #     git add Client
+      #     git commit -m "build webgl `date`"
+      #     git push
